-- ════════════════════════════════════════════════════════════
-- EnSu · Esquema de Supabase
-- Pegar entero en: Supabase → SQL Editor → New query → Run
-- Es seguro ejecutarlo más de una vez.
-- ════════════════════════════════════════════════════════════

-- Autores: usuarios con permiso de escritura (solo tú).
-- Tras crear tu usuario en Authentication, ejecuta (con tu email):
--   insert into public.autores (user_id) select id from auth.users where email = 'TU_EMAIL';
create table if not exists public.autores (
  user_id uuid primary key references auth.users(id) on delete cascade
);

-- ¿El usuario de la sesión es autor? (security definer: consulta autores sin exponerla)
create or replace function public.es_autor() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.autores where user_id = auth.uid());
$$;

-- Entradas: libros, artículos, reflexiones y privadas
create table if not exists public.entradas (
  id            bigint generated by default as identity primary key,
  tipo          text     not null default 'libro'     check (tipo in ('libro','articulo','reflexion','privado')),
  estado        text     not null default 'terminado' check (estado in ('leyendo','terminado','proximo','pendiente')),
  libro         text     not null default '',
  autor         text     not null default '',
  fecha         date,
  titulo_ref    text     not null default '',
  reflexion     text     not null default '',
  cita          text     not null default '',
  vida          text     not null default '',
  tension       text     not null default '',
  finalidad     text     not null default '',
  categoria     text     not null default '',
  dificultad    text     not null default '',
  tags          text[]   not null default '{}',
  progreso      smallint not null default 0 check (progreso between 0 and 100),
  puntuacion    smallint check (puntuacion between 1 and 10),
  paginas_total integer  check (paginas_total > 0),
  pagina_actual integer  check (pagina_actual >= 0),
  orden         integer  check (orden > 0),
  portada       text     not null default '',
  portada_id    bigint   not null default 0,
  creado        timestamptz not null default now(),
  actualizado   timestamptz not null default now()
);

-- Notas privadas: tabla aparte para que nunca viajen al público
create table if not exists public.notas_privadas (
  entrada_id  bigint primary key references public.entradas(id) on delete cascade,
  texto       text not null default '',
  actualizado timestamptz not null default now()
);

-- Tareas (solo autor)
create table if not exists public.tareas (
  id       bigint generated by default as identity primary key,
  titulo   text not null check (length(trim(titulo)) > 0),
  detalles text not null default '',
  estado   text not null default 'pendiente' check (estado in ('pendiente','en-progreso','completado')),
  fecha    date,
  creado   timestamptz not null default now()
);

-- Fecha de actualización automática
create or replace function public.tocar_actualizado() returns trigger language plpgsql as $$
begin new.actualizado = now(); return new; end $$;
drop trigger if exists entradas_actualizado on public.entradas;
create trigger entradas_actualizado before update on public.entradas
  for each row execute function public.tocar_actualizado();
drop trigger if exists notas_actualizado on public.notas_privadas;
create trigger notas_actualizado before update on public.notas_privadas
  for each row execute function public.tocar_actualizado();

-- ── Seguridad (Row Level Security) ──
alter table public.autores        enable row level security;
alter table public.entradas       enable row level security;
alter table public.notas_privadas enable row level security;
alter table public.tareas         enable row level security;

drop policy if exists "autores: solo autor" on public.autores;
create policy "autores: solo autor" on public.autores for select using (public.es_autor());

drop policy if exists "entradas: lectura publica" on public.entradas;
create policy "entradas: lectura publica" on public.entradas for select
  using (tipo <> 'privado' or public.es_autor());
drop policy if exists "entradas: escritura autor" on public.entradas;
create policy "entradas: escritura autor" on public.entradas for all
  using (public.es_autor()) with check (public.es_autor());

drop policy if exists "notas: solo autor" on public.notas_privadas;
create policy "notas: solo autor" on public.notas_privadas for all
  using (public.es_autor()) with check (public.es_autor());

drop policy if exists "tareas: solo autor" on public.tareas;
create policy "tareas: solo autor" on public.tareas for all
  using (public.es_autor()) with check (public.es_autor());

-- ── Tiempo real (la web se actualiza sola al guardar) ──
do $$ begin
  begin alter publication supabase_realtime add table public.entradas;       exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.notas_privadas; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.tareas;         exception when duplicate_object then null; end;
end $$;
