-- ════════════════════════════════════════════════════════════
-- EnSu · Mejoras (portadas propias, reto anual, historial de lectura)
-- Pegar entero en: Supabase → SQL Editor → New query → Run
-- Solo AÑADE tablas y columnas; no modifica ni borra datos. Se puede repetir.
-- ════════════════════════════════════════════════════════════

-- ── 1. Fecha en que se terminó cada libro (para el reto y el resumen del año) ──
alter table public.entradas add column if not exists terminado_en date;

-- ── 2. Ajustes (p. ej. el reto de lectura de cada año) ──
create table if not exists public.ajustes (
  clave       text primary key,
  valor       jsonb not null,
  actualizado timestamptz not null default now()
);
alter table public.ajustes enable row level security;
drop policy if exists "ajustes: lectura publica" on public.ajustes;
create policy "ajustes: lectura publica" on public.ajustes for select using (true);
drop policy if exists "ajustes: escritura autor" on public.ajustes;
create policy "ajustes: escritura autor" on public.ajustes for all
  using (public.es_autor()) with check (public.es_autor());

-- ── 3. Historial de lectura (solo autor: contiene fechas exactas) ──
create table if not exists public.lecturas_progreso (
  id         bigint generated by default as identity primary key,
  entrada_id bigint not null references public.entradas(id) on delete cascade,
  momento    timestamptz not null default now(),
  pagina     integer,
  progreso   smallint not null
);
create index if not exists lecturas_progreso_entrada on public.lecturas_progreso (entrada_id, momento);
alter table public.lecturas_progreso enable row level security;
drop policy if exists "historial: solo autor" on public.lecturas_progreso;
create policy "historial: solo autor" on public.lecturas_progreso for all
  using (public.es_autor()) with check (public.es_autor());

-- Se registra solo: cada vez que cambia el progreso o la página de un libro
create or replace function public.registrar_progreso() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.tipo = 'libro' and (
       tg_op = 'INSERT'
       or new.progreso is distinct from old.progreso
       or new.pagina_actual is distinct from old.pagina_actual) then
    insert into public.lecturas_progreso (entrada_id, pagina, progreso)
    values (new.id, new.pagina_actual, new.progreso);
  end if;
  return new;
end $$;
drop trigger if exists entradas_historial on public.entradas;
create trigger entradas_historial after insert or update on public.entradas
  for each row execute function public.registrar_progreso();

-- ── 4. Portadas propias (Supabase Storage) ──
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('portadas', 'portadas', true, 3145728, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = true, file_size_limit = 3145728,
  allowed_mime_types = array['image/jpeg','image/png','image/webp'];

drop policy if exists "portadas: subir autor" on storage.objects;
create policy "portadas: subir autor" on storage.objects for insert
  with check (bucket_id = 'portadas' and public.es_autor());
drop policy if exists "portadas: cambiar autor" on storage.objects;
create policy "portadas: cambiar autor" on storage.objects for update
  using (bucket_id = 'portadas' and public.es_autor());
drop policy if exists "portadas: borrar autor" on storage.objects;
create policy "portadas: borrar autor" on storage.objects for delete
  using (bucket_id = 'portadas' and public.es_autor());

-- ── 5. Tiempo real para las tablas nuevas ──
do $$ begin
  begin alter publication supabase_realtime add table public.ajustes;           exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.lecturas_progreso; exception when duplicate_object then null; end;
end $$;

-- Comprobación
select
  (select count(*) from information_schema.columns where table_name='entradas' and column_name='terminado_en') as columna_terminado_en,
  (select count(*) from public.ajustes) as ajustes,
  (select count(*) from storage.buckets where id='portadas') as bucket_portadas;
