-- ════════════════════════════════════════════════════════════
-- EnSu · Subrayados, notas y marcadores de lectura
-- Pegar en Supabase → SQL Editor → Run. Solo añade; no toca tus datos.
-- Son privados: solo los ve y los edita el autor.
-- ════════════════════════════════════════════════════════════
begin;

create table if not exists public.marcas (
  id         bigint generated by default as identity primary key,
  entrada_id bigint not null references public.entradas(id) on delete cascade,
  tipo       text   not null default 'subrayado' check (tipo in ('subrayado','nota','marcador')),
  cfi        text   not null,                 -- posición exacta dentro del libro
  texto      text   not null default '',      -- lo subrayado
  nota       text   not null default '',      -- lo que escribiste
  creado     timestamptz not null default now()
);
create index if not exists marcas_entrada on public.marcas (entrada_id, creado);

alter table public.marcas enable row level security;
drop policy if exists "marcas: solo autor" on public.marcas;
create policy "marcas: solo autor" on public.marcas for all
  using (public.es_autor()) with check (public.es_autor());

commit;

do $$ begin
  begin alter publication supabase_realtime add table public.marcas; exception when duplicate_object then null; end;
end $$;

-- Comprobación
select count(*) as marcas from public.marcas;
